title: CS 164
description: >- # this means to ignore newlines until "baseurl:"
  CS 164 - Programming Languages and Compilers
baseurl: ""
url: "https://mwillsey.com"

markdown: kramdown
kramdown:
  math_engine: nil

future: true

links:
  extension: "https://docs.google.com/forms/d/e/1FAIpQLSdqf_hMQixsTRvhNBMZt5Ag35ikgS6yIm41xVKzXCmGrMF4jA/viewform?usp=header"

exclude:
  - .vscode/
  - .github/
  - Makefile
  - vendor
